apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: $PG_HOST:$PG_PORT
    database: $PG_DATABASE
    user: $PG_USER
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $PG_PASSWORD
